# Generated by Django 4.0 on 2021-12-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('user_phone_num', models.TextField(max_length=64)),
                ('username', models.TextField(max_length=64)),
                ('date_time', models.TextField(max_length=64)),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),

        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.TextField(max_length=64)),
                ('channel_link', models.TextField(max_length=64)),
            ],
        ),
       
    ]
